/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
const Cube = (props) => {
  const group = useRef();
  const { nodes, materials } = useGLTF("models/rajj.glb");

  useFrame(() => {
    if (group.current) {
      group.current.rotation.y += 0.01; // Adjust the rotation speed as needed
    }
  });

  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube.geometry}
        material={materials["Material.001"]}
        position={[-0.228, 0.068, 0.043]}
        rotation={[0, 0, 0.108]}
        scale={[0.838 * 10, 10, 10]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Text.geometry}
        material={materials["Material.002"]}
        position={[0.05, -0.5, 0.1]}
        rotation={[Math.PI / 2, 0.108, -Math.PI / 2]}
        scale={[0.099 * 10, 0.099 * 10, 0.099 * 10]}
      />
    </group>
  );
};

export default Cube;
