/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import * as THREE from "three";
import { useFrame } from "@react-three/fiber";
const Next = (props) => {
  const groupRef = useRef();
  const { nodes, materials } = useGLTF("/models/Nxt.glb");

  useFrame(() => {
    if (groupRef.current) {
      groupRef.current.rotation.y += 0.008;
    }
  });

  return (
    <group ref={groupRef} {...props} dispose={null}>
      <mesh
        geometry={nodes.Cylinder.geometry}
        material={new THREE.MeshBasicMaterial({ color: "white" })}
        position={[0.4, 3.7, -0.714]}
        rotation={[-1.592, -0.025, -3.131]}
        scale={[2.013 * 0.9, 0.099 * 0.9, 1.937 * 0.9]}
      />
      <mesh
        geometry={nodes.Curve.geometry}
        material={materials["SVGMat.001"]}
        position={[-1.452, 5.588, -0.751]}
        rotation={[1.533, -0.008, -0.017]}
        scale={[29.25 * 0.9, 12.054 * 0.9, 27.874 * 0.9]}
      />
    </group>
  );
};
export default Next;
