/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

const Next = (props) => {
  const { nodes, materials } = useGLTF("/models/Nxt.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder.geometry}
        material={nodes.Cylinder.material}
        position={[0.709, 3.568, -0.714]}
        rotation={[-1.592, -0.025, -3.131]}
        scale={[2.013, 0.099, 1.937]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve.geometry}
        material={materials["SVGMat.001"]}
        position={[-1.452, 5.588, -0.751]}
        rotation={[1.533, -0.008, -0.017]}
        scale={[29.25, 12.054, 27.874]}
      />
    </group>
  );
};

useGLTF.preload("/models/Nxt.glb");
export default Next;
